version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build: .
    container_name: express-app
    ports:
      - "3004:3004"
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase

volumes:
  mongo-data:
